### PR TITLE
Add fork-corner

### PR DESCRIPTION
**Pull request by WarenGonzaga**
I add the modern and easiest way to place a [fork corner](https://github.com/warengonzaga/fork-corner) to the homepage.

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
@googlebot I fixed it.

**Comment by WarenGonzaga** [comment]
@googlebot I fixed it.

**Comment by WarenGonzaga** [comment]
@googlebot I fixed it.

**Comment by lgarron** [comment]
This site is an important piece of web security infrastructure and very internationally doesn't include any third-party content.

I appreciate the problem you're trying to solve, but your project looks fairly new and this project already has a working self-contained (vendored) GitHub ribbon that has reasonably small single-file CSS implementation with accessible fallback text.

The decision is up to @nharper but in this case I would advise to kept current approach.

**Comment by WarenGonzaga** [comment]
> This site is an important piece of web security infrastructure and very internationally doesn't include any third-party content.
> 
> I appreciate the problem you're trying to solve, but your project looks fairly new and this project already has a working self-contained (vendored) GitHub ribbon that has reasonably small single-file CSS implementation with accessible fallback text.
> 
> The decision is up to @nharper but in this case I would advise to kept current approach.

I understand, thanks for the input...

**Comment by nharper** [comment]
I agree with @lgarron that it makes sense to keep the ribbon as is.

**Comment by WarenGonzaga** [comment]
Thanks @nharper, I'm gonna close this PR.

**Pull request closed without merging**
