### PR TITLE
Update form.css

### PR DESCRIPTION
**Pull request by ZerooCool**
The text is too long and goes out of the button.
Increase the size of the button.
My resolution: 1920x1080.  

Decrease font-size: 1.4em;
Increase max-width: 22em;

.form input[type=text],
.form input[type=submit] {

  font-size: 1.4em;

  max-width: 22em;

}

### CODE REVIEW

**Comment by ZerooCool** [comment]
Replace max-width: 22em; by max-width: 25em;

**Comment by lgarron** [comment]
The button seems to have plenty of spare space for me at that resolution. Would you mind sharing screenshots before and after this change?

**Comment by ZerooCool** [comment]
https://prnt.sc/mhp2k9

And, the second button to the bottom too, for the validation ( is not in my screen ).

I have test and my notification is correct : Need more space and small text.
You can validate this update, it's my opinion.

**Comment by lgarron** [comment]
Thanks, I think this is pretty reasonable!

**Comment by ZerooCool** [comment]
For the button at the bottom, this is better : 
Replace max-width: 22em; by max-width: 25em;

Thank you for your validation.

**Pull request merged**
