### PR TITLE
README.md: Revert to the PNG logo image.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by lgarron** [comment]
Aaargh, this might have been why I used a the PNG before. I don't want viewing the README to trigger a request to GitHub for no good reason. :-/

Could we just revert to the PNG?

**Comment by XhmikosR** [comment]
But the PNG will also trigger a request... where do you think it loads it from? :P

**Comment by XhmikosR** [comment]
And to be precise both of them are 2 requests when one views the README.md file:

1. a 302 redirect
2. the image itself

**Comment by lgarron** [comment]
> But the PNG will also trigger a request... where do you think it loads it from? :P

If you have a Markdown viewer and are viewing from your checkout: your filesystem. ;-)

**Comment by XhmikosR** [comment]
Ah, that is a different case indeed.

As you wish, I'll just revert to the PNG.

**Comment by XhmikosR** [comment]
Done, just squash all of them :)

**Comment by lgarron** [comment]
I suspect this won't work on GitHub either, and we'll just have to revert the previous commit. :-(
Let me try.

**Comment by lgarron** [comment]
Looks like the PNG works!

Perhaps https://github.com/isaacs/github/issues/316 was only partially fixed.

**Pull request merged**
